language: python
python:
- 2.7
- 3.4
- 3.5
install:
- pip install tox-travis
- pip install coveralls
deploy:
  provider: pypi
  user: napalmaos
  password:
    secure: OGGLzrNk0m3PJyVGdlKukzr7sPxhAoGY5s+Mf4ED1lFVp1i4rw+l5AVbMeZExBIOKlVE31iMs+uHVav1mU8Zav0DJwmntXHt8JGenbJVi4aFcFusdWB+P4VohduO6eS9lNndbA3i1bwyHXCpquXj2FcgveyMEV6QJVHNzPOw4MFyafVxn/mN4zeWzdk0wwmAqO8hYCPI0ojdt+VcEMiD3oABSuUP97aYOFWuqI6d8S9aswJO89/63hy20rpKFaRR0oKr8rPIjUihIBG+7zf/qba4qTdyk0+pM2PU/r5eS/WVs/xoK/hR2bqIgXIKsmDE5zZMXsQDkSZ0LF6U3lSZ1U3oUfgL3hNl98N6LdgaUqltSYJrKGRxe73bM3yX2Av7waIr65Q7PLEI+UJWd4wGbLIPgCaILSE3BPsV802E3u2XmFkbrn8L9EhIQ+GQyDKB+4EluabJGRG2MUVa0vbL09UhELvn7nOCZE9DKSWwTKQtzqrmJuG7PD1TNj6jTTUY+wBKHltLwVwDEn7xvKBo82D7OxzqtbgtS58QUhfGE30Uh6utvVBRrVNKG6iDw7GafcehBX58uoQKhDtqVFCxJE4TpLDOrsVmxMieBHLnW6BJ0/ac5fyKxfXoCEPYOa84ma96vXCAQaPIf6hOoTHt9PllQq34aJwJbEl4duIHtd4=
  on:
    tags: true
    branch: master
script:
- tox
after_success:
- coveralls
