language: python
python:
- 2.7
- 3.4
- 3.5
install:
- pip install tox-travis
- pip install coveralls
deploy:
  provider: pypi
  user: napalmaos
  password:
    secure: i3KT+BS+o1XIy7+W2sMdOZ2R/5n7vF9ZjzGTHBQE2WqPqEO1p8U4biePDqnyUEBtl01CJreBfiAU6a8w7JpZsiMH/dSxgoakiZ1uy0FrmAiuhrwrrBe1KCaGbaknq5BRR68j1kEvkrSYxw4m9aUlDYfBf9+Jet/KXmsGddFwcThfhjHU2aX6LkUjrSUZtnIBlBNxyK83+4jPxCXnXn0xv2FWACfB2yKB4e1zRzkNikPf+sQhGQ/8o7/sgEJzYny7/m7gthg7ofxMgHQAzNDSlYfMksvd52+Yl16I8Eh9hC4xSmfncDfvOT4VlJboz1GTz8cMNIoGdjtQ+Lfn5dMIIGxyI3LeM6DnnGwhYZH2saFb3I/Zd9JAP7ExvncqXtkBXW/5HDUIbFuxbQg2+Ya0fkYnoavzGYnNqmbiAo4cHUj2n53r0OPLJpQLuOndyoAY1vJ1hNWkslZZCPu1mWPaZ73j4p4k6TOVcaspUfK7AJsdOvb6kb4ZMBPytqfBv60f1RbGZXaNtz1Rj2HoSG3o08tHe413cVuUu4Rs5rE+hO2Efjo93Oe8SmssXH6wzu28W9Woo8XEoOcsjtJ4Y6iDpK2IQmF9Lh2PprZ/0Mbpgu4JL52aeoVOfiFeuxej+wkK70EnpPfQwGtIvYmj/PIIs0TIPX6lO43uHmMhU2iaimo=
  on:
    tags: true
    branch: master
script:
- tox
after_success:
- coveralls
