language: python
python:
- 2.7
- 3.4
- 3.5
install:
- pip install tox-travis
- pip install coveralls
deploy:
  provider: pypi
  user: napalmaos
  password:
    secure: ghWoJKp+WulV7CpupRAIGCLoErM0GoFmeYTXFKESNxZVxOOTRyOHmXksgS9mG5qII+NEDQWCeTAZxWeS2gHnjEH/NZIOBjDPC4NRWURdFYAhX4LtDRoqiuquWQb4zKcsJ7EtvZ+pfJxFuCJsFwl3K6TaxbktddQ2l+4TP/OqkUwqyH+ueCBJ5x+fWls2Kc4UkRZFOdAkT2w17yW592LSVqzeDt2QCrN8rGvzyLsDPXiS/gC4c8+Nji0dpHGl84yS3gTahDtQElAtZStb+A38Q+oYXvYmuKJ+Xept23iPeRXOb5sDhViTrvM/lNIhYja0QZCZTcNU1JjS3J4DJZqt49F3WPyAbTs9iIPyZxGQrFTMFetd5+CPSU+QJJ5cUvsxlZPlpgGT7oTVp1mOh2fnCWFMAKQxIPpVNHasR6Gal9RYEUJEWjfMMjr3huMfE7FsKar8csyM94g6DARiJWq2MOrzaDyXxowbccXpZVZo8PaXfU6NPKJZYMlEgCNYqoldJZC1J4EVnrjMmPim0c77Ecmetst/bPfftjNSxo55UWAOVvsxICJT+Z9+FPMUSx4bfygeQgvFSgfoyXdw4pP02P9ew68QpdFxwri6VS4Y5s5LOtu5gMIJ2Hz9DfDpayZleomsER1IPeF9w/X2eHvlchyLv1PJpYd4axEDrX8DPks=
  on:
    tags: true
    branch: master
script:
- tox
after_success:
- coveralls
