language: python
python:
- 2.7
- 3.4
- 3.5
install:
- pip install tox-travis
- pip install coveralls
deploy:
  provider: pypi
  user: napalmaos
  password:
    secure: tFQm9MgLsoSKLfTgFK6OqzslbvcN0x8fZEHWbMZ+LNkBzkI9zaX90MH2Q/1NEOfPEd/TJEm9xOCNcnIXopIm5Zk/Xx5HwWWuoFoWQLq+zk3D6WzazqZQeWoOecUmbELFSDr21aHkUiuCIgE6NYvQcQHn7BPH7DWYc1hUO2bZ4vKguPMco0uMtN+gpFr9/8nkABJI2uHAilfZqfGOOriuW6cXbsEsfUjrTdN1Yxr4zNw8S33ofLnUok4wdpKiX8BmypMJIEi1Yby+7VEN3R/4BqH43xIKMIY/OBL6mbnWFTwE4UygcyilO3DF/aMiwneflGFuQS5CIVsBxZiJKG+bDDj/rUqwDP8a5uiZW53SDkjxCGXNx3u3WpWeXrH/bmXmZpuIe4rlli59GJ2jJeLoDLkLD3Z4EzIFj6/epl64Q5ds59qjQ5iHBoqatVsfX4REHDaDTl+E7ZvVmod++dyzkDBHkC0/lbUfaS02qNwInVU2nM+hEyjOjSKkd85KguP0w3UbjNt4/hbgwJjXWednnrnqsq0OJW+3avDoMI43iA/ENMWlsNTL/Vwx/HpkNQHqCWO90ton78TQUOcrFen7lxM2WaLTn4TKSaIczctBU0nj5OwROiIV5/34P5mkq3I9+6Az8mKQ+E48HY9rWcfHW01AboHidFS98OwxNz0cIdY=
  on:
    tags: true
    branch: master
script:
- tox
after_success:
- coveralls
