language: python
python:
- 2.7
- 3.4
- 3.5
install:
- pip install tox-travis
- pip install coveralls
deploy:
  provider: pypi
  user: napalmaos
  password:
    secure: f22dtN80vfdKbVMC4gfTJwA8zv1ggMhsRuRisOdyWquYV0n51Ulr5MJ3vb8nnj4U6vwYde3QzGXU1ixl4fa8CT0bHTZWOC8oe+JjMH5sjU6pRCIL0SoLur+Cfc3oou8BCDiyas/bEkxSLUt8DWWWYz3OKWvCT3FvMLqBi0f9DdFd6lu5PrMZxA3VS4I27NIJBaNP/Xl7RfDPx+NODhgGfcFXaUSR/13uOOpa8obbD+LxcKD+Lboqn8nJq5c1j9+P9Qa+7qODWrFoyF2cbfi9k0w/FCorfGoTTIBzEO1r1jZCJZfVmWipixm7aEvQD2ClwAs3y3Uf9lCQQFZrm7GOjxGU1mw57q05bYC4ynt5DqCz9Z8vcqBuk5PqrVDyejR5dVj0Gm6GV/Ct3k8ffw2SiO2U8v4TFSQfqwqvStlL3NAFBA3Q7ItbAhtnqvsRsn+9qIf7xPknzgXxNaMwIbxOvaU0ErhrAR87I5J7SfJBEkKRIFh+ev9Oislgd7YXbekN+xKsDJ2NWwXA5tsUTJ7U8jUPqW9hvfQkkMFHG4A0OR8lpZftYfFnTlhd7dWyVjcENEort6Eu239wFc6p+oOj+8gFtljI9dlHfBPip3M1v+UF8oSateek6e04/YPkEMGfXLyc6t4v46OpH8+Do4Ie2N92tKdi1LkEOM9jZl9hA+A=
  on:
    tags: true
    branch: master
script:
- tox
after_success:
- coveralls
